title: Yucheng Li's Homepage
page-top-title: Yucheng Li
top-section-bg-text: Continuous Progress
home-subtitle: Yucheng Li&ensp;|&ensp; 李雨成
copyright-text: '&copy; Yucheng Li 2023-2025. All Rights Reserved.'
